server:
  port: 8090

spring:
  application:
    name: oauth2-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/thanatos_oauth2?characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 9

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848