server:
  port: 8083
  servlet:
    context-path: /api/product

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/thanatos_data?characterEncoding=UTF-8&useSSL=false
    username: root
    password: root

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

    sentinel:
      eager: true
      transport:
        port: 8719
        dashboard: localhost:8858

mybatis:
  mapper-locations: classpath:/mapper/*.xml